name: contact_scan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.0
  http: ^0.13.4
  connectivity: ^3.0.6
  shared_preferences: ^2.0.11
  dropdown_button2: ^1.0.7
  flutter_svg:
  intl:
  mobile_scanner:
  qr_code_scanner:
  flutter_slidable:
  mailer:
  sqflite:
  url_launcher:
  csv:
  path_provider:
  permission_handler:
  flutter_email_sender:
  sentry_flutter:
  change_app_package_name:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/contactList.json
  fonts:
    - family: HelveticaNeueLight
      fonts:
        - asset: assets/font/HelveticaNeue-Light.ttf
    - family: HelveticaNeueMedium
      fonts:
        - asset: assets/font/HelveticaNeue-Medium.ttf
    - family: HelveticaNeueBold
      fonts:
        - asset: assets/font/HelveticaNeue-Bold.ttf

